### ISSUE TITLE
Feature request: Pre-moves

### ISSUE THREAD

**Issue by chadparry** [jrwats/bughouse.app#35]
I'd love to pre-move. I'd especially love if the server supports it instead of just the client, so it doesn't take any time.

**Comment by jrwats** [comment]
Clientside support is the quickest way to solve this: 57c3c79500b038d8b8820802e3964316b3e206ab
Still to come: pre-drops...

**Comment by jrwats** [comment]
pre-drops: https://github.com/jrwats/bughouse.app/commit/f68c1a356b344ac8b02104657b44b433d015975d

**Comment by jrwats** [comment]
Closing for now.  Will leave server-side predrops open as a nice-to-have
