### ISSUE TITLE
Display jitter

### ISSUE THREAD

**Issue by chadparry** [jrwats/bughouse.app#38]
I was observing a game and the right-hand board vibrated violently. It was difficult to see what was being played. When I changed the browser window size, the jitter went away. I noticed that the scrollbars were showing that the canvas was almost-but-not-quite small enough to fit in the browser window.

**Comment by jrwats** [comment]
Fixed (as far as I can tell).  Likely culprit was 2b05ed46d379d1d332d4e15a5de19abd69c2df33.  Possibly 45f1d3f01d068bc707db48420676b9593c1c6f83 also
