### ISSUE TITLE
Can't drop pieces by clicking

### ISSUE THREAD

**Issue by chadparry** [jrwats/bughouse.app#53]
I can drop pieces by dragging. But I can't select a piece by clicking and then select a square by clicking. Note that I can move any pieces already on the board by clicking.

Fixing this would probably mitigate https://github.com/jrwats/bughouse.app/issues/52 , since that bug might be related to dragging.

**Comment by jrwats** [comment]
Fixed with https://github.com/jrwats/bughouse.app/commit/b99798a66d0aa650bee319a7d467bd4027c82b62
