### ISSUE TITLE
Post-game rotation

### ISSUE THREAD

**Issue by chadparry** [jrwats/bughouse.app#60]
When I visit the analysis board, I expect to see myself in the lower left where I was playing. Instead, it rotates the boards to the position I was in before the game started.

**Comment by chadparry** [comment]
Here's a screenshot of a repo: https://discord.com/channels/886375038993977365/886375039472123945/910757221850284042

**Comment by jrwats** [comment]
Apparently repro'ng.  Gotta revisit

**Comment by jrwats** [comment]
Got it to repro with "the_other_john" (white player, board B) here:
https://bughouse.app/analysis/*bcFQvs5geNCITqYDJ0xhi
